# Generated by Django 3.1.2 on 2020-10-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Paragraph',
            field=models.TextField(),
        ),
    ]
